name: tests

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
  workflow_dispatch:

env:
  COBOL4J_LIB_DIR: /usr/lib/opensourcecobol4j
  COBOL4J_LIBCOBJ_JAR_PATH: /usr/lib/opensourcecobol4j/libcobj.jar
  OCESQL4J_LIB_DIR: /usr/lib/Open-COBOL-ESQL-4j
  OCESQL4J_OCESQL4J_JAR_PATH: /usr/lib/Open-COBOL-ESQL-4j/ocesql4j.jar
  CLASSPATH: ":/usr/lib/Open-COBOL-ESQL-4j/ocesql4j.jar"


jobs:
  doc:
    runs-on: ubuntu-latest
    
    steps:
      # Install dependencies (Ubuntu 22.04)
      - name: Install dependencies on Ubuntu 22.04
        if: matrix.os == 'ubuntu:22.04'
        run: |
          sudo apt update -y
          sudo apt install -y build-essential bison flex gettext texinfo automake autoconf curl

      # Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11

      # Setup sbt
      - name: Setup sbt
        uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.11

      # Checkout
      - name: Checkout Open-COBOL-ESQL-4j
        uses: actions/checkout@v4

      # Build documentation
      - name: Install Open COBOL ESQL 4J
        run: |
          cp $COBOL4J_LIBCOBJ_JAR_PATH dblibj/lib
          cd dblibj/
          sbt doc

      # Archive documentation 
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: dblibj-docs 
          path: dblibj/target/scala-2.13/api