name: static analysis

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Open COBOL ESQL 4J
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # Install static analysis tools
      - name: Install static analysis tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format cppcheck

      # check if source code is formatted
      - name: Check format with clang-format
        run: |
          ./check-format

      # Check C files in ocesql/ using cppcheck 
      - name: Run cppcheck
        working-directory: ocesql
        run: |
         ./cppcheck 

      # Check Scala files in dblibj/ using Scalastyle
      - name: Run Scalastyle
        run: |
          cd dblibj && sbt scalastyle