name: static analysis

on:
  workflow_call:

permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Open COBOL ESQL 4J
        uses: actions/checkout@v5

      # Install static analysis tools
      - name: Install static analysis tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format cppcheck

      # Setup sbt
      - name: Setup sbt
        run: |
          curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && echo Y | ./cs setup
          echo PATH="$PATH:/home/runner/.local/share/coursier/bin" >> "$GITHUB_ENV"

      # check if source code is formatted
      - name: Check format with clang-format
        run: |
          ./check-format

      # Check C files in ocesql/ using cppcheck 
      - name: Run cppcheck
        working-directory: ocesql
        run: |
         ./cppcheck 

      # Check Scala files in dblibj/ using Scalastyle
      - name: Run Scalastyle
        run: |
          cd dblibj && sbt scalastyle